name: Continuous Integration 

on:
  push:
    branches:
     - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
      - name: Build the service1 Docker image
        run: |
          docker build ./service1/ --tag ghcr.io/adelic99/service1:${{ env.RELEASE_VERSION }}
      
      - name: Test service1
        run: |
          #pytest
          
      - name: Publish the service1 Docker image
        run: |
          docker push ghcr.io/adelic99/service1:${{ env.RELEASE_VERSION }}
      
      - name: Build the service2 Docker image
        run: |
          docker build ./service2/ --tag ghcr.io/adelic99/service2:${{ env.RELEASE_VERSION }}
          
      - name: Test service2
        run: |
          #pytest
          
      - name: Publish the service2 Docker image
        run: |
          docker push ghcr.io/adelic99/service2:${{ env.RELEASE_VERSION }}
